name: Release QA

on:
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy_qa:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: start remote ansible file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{vars.QA_SSH_HOST}}
          username: ${{vars.QA_SSH_USER}}
          password: ${{secrets.QA_SSH_PASSWORD}}
          key: ${{secrets.QA_SSH_KEY}}
          script: |
            cd /root/imshaby-deploy
            ansible-playbook ./staging.yaml --extra-vars "service_name=cms cms_tag=${{ needs.create_tag.outputs.tag }} postgres_port=${{ vars.QA_POSTGRES_PORT }} postgres_username=${{ vars.QA_POSTGRES_USERNAME }} postgres_password=${{ secrets.QA_POSTGRES_PASSWORD }} postgres_db=${{ secrets.QA_POSTGRES_DB }} node_env=${{ vars.QA_NODE_ENV }} app_keys=${{ secrets.QA_APP_KEYS }} admin_jwt_secret=${{ secrets.QA_ADMIN_JWT_SECRET }} api_token_salt=${{ secrets.QA_API_TOKEN_SALT }} transfer_token_salt=${{ secrets.QA_TRANSFER_TOKEN_SALT }} jwt_secret=${{ secrets.QA_JWT_SECRET }} access_key_id=${{ secrets.QA_ACCESS_KEY_ID }} access_secret_key=${{ secrets.QA_ACCESS_SECRET_KEY }}"
