name: Release QA

on:
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: create_tag

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.create_tag.outputs.tag }}

      # Runs a single command using the runners shell
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v0.1-alpha
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}


      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crp8o64j2cl644b4pjki
          CR_REPOSITORY: imshaby-cms-qa
          IMAGE_TAG: ${{ needs.create_tag.outputs.tag }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG -f ./Dockerfile.prod .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

  deploy_qa:
    runs-on: ubuntu-latest
    needs: [create_tag, build]
    steps:
      - name: start remote ansible file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{vars.QA_SSH_HOST}}
          username: ${{vars.QA_SSH_USER}}
          password: ${{secrets.QA_SSH_PASSWORD}}
          key: ${{secrets.QA_SSH_KEY}}
          script: |
            cd /root/imshaby-deploy
            ansible-playbook ./staging.yaml --extra-vars "service_name=cms docker_image=cr.yandex/crp8o64j2cl644b4pjki/imshaby-cms-qa:${{ needs.create_tag.outputs.tag }} postgres_port=${{ vars.QA_POSTGRES_PORT }} postgres_username=${{ vars.QA_POSTGRES_USERNAME }} postgres_password=${{ secrets.QA_POSTGRES_PASSWORD }} postgres_db=${{ secrets.QA_POSTGRES_DB }} node_env=${{ vars.QA_NODE_ENV }} app_keys=${{ secrets.QA_APP_KEYS }} admin_jwt_secret=${{ secrets.QA_ADMIN_JWT_SECRET }} api_token_salt=${{ secrets.QA_API_TOKEN_SALT }} transfer_token_salt=${{ secrets.QA_TRANSFER_TOKEN_SALT }} jwt_secret=${{ secrets.QA_JWT_SECRET }} access_key_id=${{ secrets.QA_ACCESS_KEY_ID }} access_secret_key=${{ secrets.QA_ACCESS_SECRET_KEY }}"
